config/routes.rb
Plagbook::Application.routes.draw do
  mount RailsAdmin::Engine => '/db_admin', :as => 'rails_admin'

  devise_for :admins

  get "subjects/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :subjects
  resources :assignments
  
  resources :users do
    collection do
      get 'stats'
    end
  end
  
  resources :general_profiles, only: [:update] do
    collection do
      get 'adjust_profile'      
    end
  end
  
  resources :solutions do
    collection do
      get 'suspicious'
      get 'delete_all'
      get 'recompute'
    end
  end
  
  root to: 'static_pages#home'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup',  to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @solution = current_user.solutions.build if signed_in?
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Plagbook</h1>

<p>
	The idea is to create programming profile for each student based on metrics extracted from submitted assignments.
	The metrics are:
	general - average line length, white space distribution, loop type preference..
	programming language specific - use of javadoc, exception handling..
	+my own metrics - prefered programming language, used IDE, usage of blank lines for better code readability..
	<br />
	<br />
	When student submits new solution, system compares it's attributes with student' profile. If the difference
	exceeds defined treshold, solution is marked as suspicious. System then compares it with profiles of other students
	in given class and identifies students who are most likely to be the real author of given solution.
	<br />
	After each submitted solution, user's profile is refined (unless it is suspicious) so we should have more precise results
	as time goes on.
	<br />
	Designed for Java and C/C++ source codes.
	<br />
	<br />
	Ruby 1.9.2p290<br />
	Rails 3.2<br />
	Mysql 
</p>
<p>
	<a href="http://www.miloshes.sk/">Author's personal webpage</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
   Any questions can be addressed to ja[at]miloshes.sk
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? && teacher? %>
	<%= link_to "Add new assignment", new_assignment_path, class: "signup_button round" %>
	<br/>
	<%= link_to "Add new solution", new_solution_path, class: "signup_button round" %>
	<br/>
	<%= link_to "Show suspicious solutions", "/solutions/suspicious", class: "signup_button round" %>
	<br/>
	<%= link_to "Re-compute data", "/solutions/recompute", class: "signup_button round" %>
<% else %>
<h1>Welcome to Plagbook</h1>
<p>
   This is the homepage for online antiplagiarism system
</p>
<%= link_to "Sign in", signin_path, class: "signup_button round" %>
<br/>
<p align="center">OR</p>
<%= link_to "Create new teacher", signup_path, class: "signup_button round" %>
<% end %>