config/routes.rb
Plagbook::Application.routes.draw do
  mount RailsAdmin::Engine => '/db_admin', :as => 'rails_admin'

  devise_for :admins

  get "subjects/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :subjects
  resources :assignments
  
  resources :users do
    collection do
      get 'stats'
    end
  end
  
  resources :general_profiles, only: [:update] do
    collection do
      get 'adjust_profile'      
    end
  end
  
  resources :solutions do
    collection do
      get 'suspicious'
      get 'delete_all'
      get 'recompute'
    end
  end
  
  root to: 'static_pages#home'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup',  to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :text
#  tags        :text
#  subject_id  :integer(4)
#  created_at  :datetime
#  updated_at  :datetime
#

class Assignment < ActiveRecord::Base
  attr_accessible :name, :tags, :description, :subject_id
  
  validates :name, presence: true
  
  has_and_belongs_to_many :prog_languages
  belongs_to :subject
  has_many :solutions, dependent: :destroy
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  
  def index
    @assignments = Assignment.paginate(page: params[:page])  
  end
  
  def new
    @assignment = Assignment.new
  end
  
  def create
    @assignment = Assignment.new(params[:assignment])
    
    if @assignment.save
      flash[:success] = "Assignment '#{@assignment.name}' successfuly created."
      redirect_to assignments_path
    else
      render 'new'
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<tr>
  <td class="assignments">
  	<span class="title"><%= assignment.name%></span>
  </td>	
  <td class="assignments">
    <span class="teacher_name"><%= assignment.subject.title %></span>
  </td>
  <td class="assignments">
    <span class="timestamp"><%= assignment.tags %></span>
  </td>
</tr>

app/views/assignments/index.html.erb
<% provide :title, 'All assignments' %>
<h1>All assignments</h1>

<%= will_paginate %>

 <table class="assignments">
 	<th>Name</th>
 	<th>Subject</th>
 	<th>Tags</th>
 	<%= render @assignments %>
 </table>

<%= will_paginate %>

app/views/assignments/new.html.erb
<%= provide(:title, 'New Assignment') %>
<h1>New assignment</h1>
<br />

<%= form_for(@assignment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
   <div class="field">
    <%= f.label :subject %>
    <br/>
    <%= f.select :subject_id, Subject.all.collect{ |subject| [subject.title, subject.id]} %>
    &nbsp; <%= link_to "Add new subject", new_subject_path %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <br/>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </div>
 
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>