config/routes.rb
Plagbook::Application.routes.draw do
  mount RailsAdmin::Engine => '/db_admin', :as => 'rails_admin'

  devise_for :admins

  get "subjects/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :subjects
  resources :assignments
  
  resources :users do
    collection do
      get 'stats'
    end
  end
  
  resources :general_profiles, only: [:update] do
    collection do
      get 'adjust_profile'      
    end
  end
  
  resources :solutions do
    collection do
      get 'suspicious'
      get 'delete_all'
      get 'recompute'
    end
  end
  
  root to: 'static_pages#home'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup',  to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_filter :signed_in_user
  
  require 'iconv'
  
  def new
    @solution = Solution.new
    if(params[:user_id])
      @default = params[:user_id]
    else
      @defalt = 1
    end    
  end
  
  def show
    @solution = Solution.find(params[:id])
    
    #general profile
    solution_gen_profile = GeneralProfile.find(@solution.general_profile.id, select: "id, avg_line_length, ws_distribution, words_per_line,
                                         avg_fun_length, avg_comm_length, comm_code_ratio, single_comm_ratio,
                                         multi_comm_ratio, for_loop_ratio, while_loop_ratio, do_loop_ratio,
                                         var_english_ratio, comm_english_ratio, avg_var_length, avg_fun_name_length", limit: 1)
                                         
    @gen_attributes_count = solution_gen_profile.attributes.values.size-1
    @gen_attributes_names = solution_gen_profile.attributes.keys
    @gen_solution_values = solution_gen_profile.attributes.values
    
    if(JOIN_PROFILES == true)
      gen_comparison = Comparison.where(profile_type: PROFILE_JOINED, solution_profile_id: solution_gen_profile.id,
                                      student_profile_id: @solution.user.general_profile.id).first
                                      
      if(@solution.is_suspicious?)
        @gen_chart = []
        comparisons = Comparison.find(:all, conditions: "solution_profile_id = #{@solution.general_profile.id} AND profile_type = " + "\"" + PROFILE_JOINED + @solution.prog_language.language + "\"", order: 'distance ASC')
        comparisons.each do |comparison|
          @gen_chart.push([GeneralProfile.find(comparison.student_profile_id).user, comparison.distance])
        end
      end 
    else
      gen_comparison = Comparison.where(profile_type: PROFILE_GENERAL, solution_profile_id: solution_gen_profile.id,
                                      student_profile_id: @solution.user.general_profile.id).first
    end                                   
                                     
    case @solution.prog_language_id
      when LANG_JAVA
        solution_lang_profile = JavaProfile.find(@solution.java_profile.id, select: "id, javadoc_ratio, try_catch_ratio,
                                                  throws_ratio", limit: 1)
        
        @lang_attributes_count = solution_lang_profile.attributes.values.size-1
        @lang_attributes_names = solution_lang_profile.attributes.keys
        @lang_solution_values = solution_lang_profile.attributes.values
    
        lang_comparison = Comparison.where(profile_type: PROFILE_JAVA, solution_profile_id: solution_lang_profile.id,
                                      student_profile_id: @solution.user.java_profile.id).first
                                      
        if(lang_comparison)
          student_lang_profile = JavaProfile.find(lang_comparison.student_profile_id, select: "id, javadoc_ratio, try_catch_ratio,
                                                  throws_ratio", limit: 1)
          
          @lang_distance = lang_comparison.distance
          @lang_student_values = student_lang_profile.attributes.values
          
          if(COMPARISON_METHOD == "distance_measure")
            @lang_solution_vec_len = JavaProfile.distance_vector_length(@lang_solution_values[1..-1])  #leaving out id
            @lang_student_vec_len = JavaProfile.distance_vector_length(@lang_student_values[1..-1])
          else
            @lang_solution_vec_len = JavaProfile.euclidian_vector_length(@lang_solution_values[1..-1])
            @lang_student_vec_len = JavaProfile.euclidian_vector_length(@lang_student_values[1..-1])
            #hmm sqrt(a) + sqrt(b) != sqrt(a+b)
          end
        end
      when LANG_C
        solution_lang_profile = CProfile.find(@solution.c_profile.id, select: "id, unary_ratio, short_operator_ratio", limit: 1)
        
        @lang_attributes_count = solution_lang_profile.attributes.values.size-1
        @lang_attributes_names = solution_lang_profile.attributes.keys
        @lang_solution_values = solution_lang_profile.attributes.values
        
        lang_comparison = Comparison.where(profile_type: PROFILE_C, solution_profile_id: solution_lang_profile.id,
                                      student_profile_id: @solution.user.c_profile.id).first
                                      
        if(lang_comparison)
          student_lang_profile = CProfile.find(lang_comparison.student_profile_id, select: "id, unary_ratio, short_operator_ratio", limit: 1)
          
          @lang_distance = lang_comparison.distance
          @lang_student_values = student_lang_profile.attributes.values
      
          if(COMPARISON_METHOD == "distance_measure")
            @lang_solution_vec_len = GeneralProfile.distance_vector_length(@lang_solution_values[1..-1])  #leaving out id
            @lang_student_vec_len = GeneralProfile.distance_vector_length(@lang_student_values[1..-1])
          else
            @lang_solution_vec_len = GeneralProfile.euclidian_vector_length(@lang_solution_values[1..-1])
            @lang_student_vec_len = GeneralProfile.euclidian_vector_length(@lang_student_values[1..-1])
            #hmm sqrt(a) + sqrt(b) != sqrt(a+b)
          end
        end
    end
    
    if(gen_comparison)
      student_gen_profile = GeneralProfile.find(gen_comparison.student_profile_id, select: "id, avg_line_length, ws_distribution, words_per_line,
                                         avg_fun_length, avg_comm_length, comm_code_ratio, single_comm_ratio,
                                         multi_comm_ratio, for_loop_ratio, while_loop_ratio, do_loop_ratio,
                                         var_english_ratio, comm_english_ratio, avg_var_length, avg_fun_name_length", limit: 1)
      @gen_distance = gen_comparison.distance
      @gen_student_values = student_gen_profile.attributes.values
      
      if(COMPARISON_METHOD == "distance_measure")
        @gen_solution_vec_len = GeneralProfile.distance_vector_length(@gen_solution_values[1..-1])  #leaving out id
        @gen_student_vec_len = GeneralProfile.distance_vector_length(@gen_student_values[1..-1])
      else
        @gen_solution_vec_len = GeneralProfile.euclidian_vector_length(@gen_solution_values[1..-1])
        @gen_student_vec_len = GeneralProfile.euclidian_vector_length(@gen_student_values[1..-1])
        #hmm sqrt(a) + sqrt(b) != sqrt(a+b)
      end
      
      if(@solution.suspicious)
        if(COMPARE_PROFILES)
          comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_GENERAL}' AND solution_profile_id = #{solution_gen_profile.id} AND student_profile_id != #{student_gen_profile.id}",
                                        order: 'distance DESC')
          
          if(comparisons.count > 0)
            @gen_chart = []
            comparisons.each do |comparison|
              @gen_chart.push([GeneralProfile.find(comparison.student_profile_id).user, comparison.distance])
            end
          end
          
          case @solution.prog_language_id
            when LANG_JAVA          
              comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_JAVA}' AND solution_profile_id = #{solution_gen_profile.id} AND student_profile_id != #{student_gen_profile.id}",
                                            order: 'distance DESC')
              if(comparisons.count > 0)
                @java_chart = []
                comparisons.each do |comparison|
                  @java_chart.push([JavaProfile.find(comparison.student_profile_id).user, comparison.distance])
                end
              end
              
            when LANG_C
              comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_C}' AND solution_profile_id = #{solution_gen_profile.id} AND student_profile_id != #{student_gen_profile.id}",
                                            order: 'distance DESC')
              if(comparisons.count > 0)
                @c_chart = []
                comparisons.each do |comparison|
                  @c_chart.push([CProfile.find(comparison.student_profile_id).user, comparison.distance])
                end
              end
          end
          
        else
           
          comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_GENERAL+"-solutions"}' AND solution_profile_id = #{solution_gen_profile.id}",
                                        order: 'distance DESC')
                                        
          if(comparisons.count > 0)
            @gen_chart = []
            comparisons.each do |comparison|
              profile = GeneralProfile.find(comparison.student_profile_id)
              @gen_chart.push([profile.solution.user, profile.solution, comparison.distance])
            end
          end
          
          case @solution.prog_language_id
          when LANG_JAVA
            comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_JAVA+"-solutions"}' AND solution_profile_id = #{solution_gen_profile.id}",
                                          order: 'distance DESC')
                                          
            if(comparisons.count > 0)
              @java_chart = []
              comparisons.each do |comparison|
                profile = JavaProfile.find(comparison.student_profile_id)
                @java_chart.push([profile.solution.user, profile.solution, comparison.distance])
              end
            end
          when LANG_C
            comparisons = Comparison.find(:all, conditions: "profile_type = '#{PROFILE_C+"-solutions"}' AND solution_profile_id = #{solution_gen_profile.id}",
                                          order: 'distance DESC')
                                          
            if(comparisons.count > 0)
              @c_chart = []
              comparisons.each do |comparison|

app/views/solutions/_solution.html.erb
<tr>
  <td class="solutions">
  	<span class="filename"><%= link_to solution.filename, solution %></span>
  </td>	
  <td class="solutions">
    <span class="ass_name"><%= solution.assignment.name %></span>
  </td>
  <td class="solutions">
    <span class="timestamp"><%= solution.created_at.strftime("%d.%m.%Y-%H:%M:%S") %></span>
  </td>
</tr>

app/views/solutions/new.html.erb
<%= provide(:title, 'New Solution') %>
<h1>New solution</h1>
<br />
<%= form_for(@solution) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :student %>
    <br/>
    <%= f.select :user , User.where(group_id: 3).collect{|student|[student.full_name, student.id]}, include_blank: true, selected: @default %>
    &nbsp;<%= link_to "Add new student", new_user_path %>
  </div>
  <div class="field">
    <%= f.label :assignment %>
    <br/>
    <%= f.select :assignment, Assignment.all.collect{|ass|[ass.name + " (" + ass.subject.title + ")", ass.id]} %>
    &nbsp;<%= link_to "Add new assignment", new_assignment_path %>
  </div>
  <div class="field">
  	<%= f.label :programming_language%>
  	<br/>
    <%= f.select :prog_language, ProgLanguage.all.collect{|lang|[lang.language, lang.id]}%>
  </div>
  <div class="field">
    <%= f.label :source_code %>
    <br/>
    <%= f.file_field :filename, multiple: true%>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

app/views/solutions/show.html.erb
<% provide :title, @solution.filename %>
	<%= link_to 'Upload assignment', new_solution_path(user_id: @solution.user_id) %>
	<h1>
   		<%= @solution.filename + " (#{@solution.prog_language.language})" %>
    </h1>
    
    <strong>Student: </strong><%= link_to @solution.user.full_name, user_path(@solution.user) %>&nbsp;
    <strong>Subject: </strong><%= link_to @solution.assignment.subject.title, subject_path(@solution.assignment.subject_id) %>&nbsp;
    <strong>Assignment: </strong><%= link_to @solution.assignment.name, assignment_path(@solution.assignment.id) %>
    <br/>
    <br/>
    
    <% if(@gen_student_values) %>
    	<%= link_to "Adjust profile", "/general_profiles/adjust_profile?id=#{@solution.id}", class: "signup_button round" %>
    <% end %>
    
    <% if(@gen_chart) %>
    	<h3>Possible real authors comparing general profiles:</h3>
    	<table class="comparisons">
          <tr>
          	<th>Student</th><th>Comparison</th>
          </tr>
          <% @gen_chart.each do |comparison| %>
          	<tr>
          		<% if(COMPARE_PROFILES) %>
	          		<td><%= comparison[0].full_name %></td>
	          		<td><%= comparison[1] %></td>
          		<% else %>
          			<td><%= comparison[0].full_name + " (" + comparison[1].filename + ")"%></td>
	          		<td><%= comparison[2] %></td>
          		<% end %>
          	</tr>
          <% end %>
        </table>
    <% end %>
    
    <% if(@java_chart) %>
    	<h3>Possible real authors comparing java profiles:</h3>
    	<table class="comparisons">
          <tr>
          	<th>Student</th><th>Comparison</th>
          </tr>	
          <% @java_chart.each do |comparison| %>
          	<tr>
          		<% if(COMPARE_PROFILES) %>
	          		<td><%= comparison[0].full_name %></td>
	          		<td><%= comparison[1] %></td>
          		<% else %>
          			<td><%= comparison[0].full_name + " (" + comparison[1].filename + ")"%></td>
	          		<td><%= comparison[2] %></td>
          		<% end %>
          	</tr>
          <% end %>
        </table>
    <% end %>
    
    <% if(@c_chart) %>
    	<h3>Possible real authors comparing c profiles:</h3>
    	<table class="comparisons">
          <tr>
          	<th>Student</th><th>Comparison</th>
          </tr>	
          <% @c_chart.each do |comparison| %>
          	<tr>
          		<% if(COMPARE_PROFILES) %>
	          		<td><%= comparison[0].full_name %></td>
	          		<td><%= comparison[1] %></td>
          		<% else %>
          			<td><%= comparison[0].full_name + " (" + comparison[1].filename + ")"%></td>
	          		<td><%= comparison[2] %></td>
          		<% end %>
          	</tr>
          <% end %>
        </table>
    <% end %>
    
    <br/>
    <% if(@gen_student_values) %>
        <h3>General profiles overall comparison: <%= @gen_distance %></h3>
	    <table class="general_profile">
	    	<th></th><th>Solution</th><th>Student</th><th>&Delta;</th>
	    	<% for i in(1..@gen_attributes_count) %>	<!-- from 1 to leave out id column-->
	    		<tr>
	    			<th><%= @gen_attributes_names[i] %></th>
	    			<td><%= @gen_solution_values[i] %></td>
	    			<td><%= @gen_student_values[i] %></td>
	    			<td><%= format("%.6f",(@gen_solution_values[i] - @gen_student_values[i]).abs) %></td>
	    		</tr>
	    	<% end %>
	    </table>
    <% else %>
    	<h3>General profile - BASE</h3>
    	<table class="general_profile">
    		 <% for i in(1..@gen_attributes_count) %>
			 	<tr>
	    			<th><%= @gen_attributes_names[i] %></th>
	    			<td><%= @gen_solution_values[i] %></td>
	    		</tr>
	    	 <% end %>
	    </table>
    <% end %>
    
    <br/>
    <% if(@lang_student_values) %>
        <h3><%= @solution.prog_language.language.upcase + " profiles overall comparison: " + @lang_distance.to_s %></h3>
	    <table class="general_profile">
	    	<th></th><th>Solution</th><th>Student</th><th>&Delta;</th>
	    	<% for i in(1..@lang_attributes_count) %>	<!-- from 1 to leave out id column-->
	    		<tr>
	    			<th><%= @lang_attributes_names[i] %></th>
	    			<td><%= @lang_solution_values[i] %></td>
	    			<td><%= @lang_student_values[i] %></td>
	    			<td><%= format("%.6f",(@lang_solution_values[i] - @lang_student_values[i]).abs) %></td>
	    		</tr>
	    	<% end %>
	    </table>
    <% else %>
    	<h3><%= @solution.prog_language.language.upcase %> profile - BASE</h3>
    	<table class="general_profile">
    		 <% for i in(1..@lang_attributes_count) %>
			 	<tr>
	    			<th><%= @lang_attributes_names[i] %></th>
	    			<td><%= @lang_solution_values[i] %></td>
	    		</tr>
	    	 <% end %>
	    </table>
    <% end %>
    
    <textarea rows="30" width="800px" cols="800" wrap="off"><%= @solution.source_code %></textarea>
      
   
      <!-- <%= link_to 'Upload assignment', new_solution_path %> -->

app/views/solutions/suspicious.html.erb
<% provide :title, "Suspicious solutions" %>

	<h1>List of suspicious solutions</h1>
		
	<table class="solutions">
    	<tr>
        	<th>Student</th><th>Author</th>
        </tr>
        <% @suspicious_solutions.each do |solution| %>
        	<tr>
        		<td class="solutions">
  					<span class="filename"><%= link_to solution.filename, solution %></span>
  				</td>	
	      		
	      		<td><%= solution.user.full_name %></td>
	      	</tr>
		<% end %>
	</table>