config/routes.rb
Plagbook::Application.routes.draw do
  mount RailsAdmin::Engine => '/db_admin', :as => 'rails_admin'

  devise_for :admins

  get "subjects/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :subjects
  resources :assignments
  
  resources :users do
    collection do
      get 'stats'
    end
  end
  
  resources :general_profiles, only: [:update] do
    collection do
      get 'adjust_profile'      
    end
  end
  
  resources :solutions do
    collection do
      get 'suspicious'
      get 'delete_all'
      get 'recompute'
    end
  end
  
  root to: 'static_pages#home'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup',  to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  	
  	Comparison: <b><%= COMPARISON_METHOD %></b></br>
  	Profile adjustment method: <b><%= PROFILE_ADJUSTMENT_METHOD %></b></br>
  	Language specific profiles: <b><%= JOIN_PROFILES.to_s %></b></br>
  	Use attribute weight: <b><%= WEIGHTENING.to_s %></b></br>
  	Number of base solutions: <b><%= NUMBER_OF_BASE_SOLUTIONS.to_s %></b></br>
  	Adjustment treshold: <b><%= ADJUSTMENT_TRESHOLD.to_s %></b></br>
  	
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", alt: "Sample App", class: "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      
      <% if signed_in? %>
      	<li><%= link_to "Users", users_path %></li>
      	<li><%= link_to "Stats", "/users/stats" %></li>
        <li><%= link_to current_user.first_name, edit_user_path(current_user) %></li>
      <% end %>
      
      <% if signed_in? %>
  		<li><%= link_to "Sign out", signout_path, method: :delete %></li>
	  <% else %>
  		<li><%= link_to "Sign in", signin_path %></li>
	  <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  media: 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
   <%= render 'layouts/stylesheets' %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
      <%= render 'layouts/header' %>

      <section class="round">
      	<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        
        <%= yield %>
      </section>
      
	  <%= render 'layouts/footer' %>
</div>
</body>
</html>